expose observer and once prop for more control over IO instance
metonym/svelte-intersection-observer pull request #11
Opened 2021-02-23 18:38 UTC by dysfunc

This PR includes a couple of enhancements that do not impact the current interface.

Changes include:
- Exposing the `IntersectionObserver` instance via `observer` which will allow more control over the IO instance.
- Adds a new dispatch event `intersect` for intersecting only events. 
- New `once` attribute that will `unobserve` once the element(s) have met the intersection threshold.
- Use strict equality checks where it makes sense

Using `once`:
```svelte
<IntersectionObserver once={true} {element}>
  <div bind:this={element}>Hello world</div>
</IntersectionObserver>
````

Using `interesect` and stop watching using `unobserve` with `observer`:
```svelte
<script>
  import IntersectionObserver from "svelte-intersection-observer";
  
  let element;
  let observer;

  const onIntersectHandler = (entry) => {
    if (someCondition) {
      observer.unobserve(entry.details.target); // or (element)
    }
  }
</script>

<IntersectionObserver {element} bind:observer on:intersect={onIntersectHandler}>
  <div bind:this={element}>Hello world</div>
</IntersectionObserver>
````

2021-02-23 21:48 UTC, metonym commented on src/IntersectionObserver.svelte
> +  /** @type {null | Observer} */
```suggestion
  /** @type {null | IntersectionObserver} */
```

The TypeScript interface is [`IntersectionObserver` ](https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L9701).

2021-02-23 21:49 UTC, metonym commented on src/IntersectionObserver.svelte
> +  export let observer = undefined;
```suggestion
  export let observer = null;
```

To be consistent with the JSDoc type.

2021-02-23 21:49 UTC, metonym commented on types/IntersectionObserver.d.ts
> +  observer?: null | Observer;
```suggestion
  observer?: null | IntersectionObserver;
```

2021-02-23 21:49 UTC, metonym commented on types/IntersectionObserver.d.ts
> +  once?: null | boolean;
```suggestion
  once?: boolean;
```

2021-02-23 21:50 UTC, metonym commented on types/IntersectionObserver.d.ts
> +  { default: { intersecting: boolean; entry: Entry, observer: Observer, once: boolean; } }
```suggestion
  { default: { intersecting: boolean; entry: Entry; observer: IntersectionObserver; } }
```

The `once` prop isn't passed to the default slot. Assuming this is a typo

2021-02-23 21:52 UTC, metonym requested changes
Thanks for taking the time to submit this PR.

The features you propose are reasonable. See my comments.

2021-02-24 00:47 UTC, dysfunc commented on types/IntersectionObserver.d.ts
> +  { default: { intersecting: boolean; entry: Entry, observer: Observer, once: boolean; } }
Yes, this was also leftover stuff I meant to remove.

2021-02-24 00:47 UTC, dysfunc commented on src/IntersectionObserver.svelte
> +  /** @type {null | Observer} */
Oops, bad copy/paste. 👍

2021-02-24 01:22 UTC, metonym commented on types/IntersectionObserver.d.ts
> +  { intersect: CustomEvent<Entry> },
`intersect` has to be in the same parameter as `observe`

2021-02-24 01:23 UTC, metonym requested changes
See my comment about typing events in the TypeScript definition. Events must be in the same parameter.

2021-02-24 01:46 UTC, dysfunc commented on types/IntersectionObserver.d.ts
> +  { intersect: CustomEvent<Entry> },
I included that change and squashed all the previous commits.

2021-02-24 01:52 UTC, dysfunc commented on types/IntersectionObserver.d.ts
> +  { intersect: CustomEvent<Entry> },
do you want me to add `[sveld](https://github.com/IBM/sveld)` in a separate PR so type definitions are generated automatically? manually typing them clearly leads to errors 😃

2021-02-24 13:11 UTC, metonym approved these changes

2021-02-24 13:12 UTC, merged

2021-02-24 13:18 UTC, metonym commented
Published to NPM in v0.6.0

2021-02-24 13:20 UTC, metonym commented on types/IntersectionObserver.d.ts
> +  { intersect: CustomEvent<Entry> },
Unfortunately sveld wouldn't work well in this use case. For example, the name of the component clashes with the `IntersectionObserver` type (https://github.com/metonym/svelte-intersection-observer/pull/11/commits/ceb18e86998b7af30850974a79abf9a68ca4c7ce). However, manually maintaining the types for a single component is acceptable IMO

2021-02-24 15:45 UTC, dysfunc commented on types/IntersectionObserver.d.ts
> +  { intersect: CustomEvent<Entry> },
Agree. I just wanted to throw it out there as an option.